/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as VoteElectionIdRouteImport } from './routes/vote.$electionId'
import { Route as SetupTokenRouteImport } from './routes/setup.$token'
import { Route as ResultsElectionIdRouteImport } from './routes/results.$electionId'
import { Route as VoteElectionIdCastRouteImport } from './routes/vote.$electionId.cast'
import { Route as ApiPublicSeedSevsRouteImport } from './routes/api/public/seed-sevs'
import { Route as ApiPublicResultsStreamElectionIdRouteImport } from './routes/api/public/results-stream.$electionId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteElectionIdRoute = VoteElectionIdRouteImport.update({
  id: '/vote/$electionId',
  path: '/vote/$electionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTokenRoute = SetupTokenRouteImport.update({
  id: '/setup/$token',
  path: '/setup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsElectionIdRoute = ResultsElectionIdRouteImport.update({
  id: '/results/$electionId',
  path: '/results/$electionId',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteElectionIdCastRoute = VoteElectionIdCastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => VoteElectionIdRoute,
} as any)
const ApiPublicSeedSevsRoute = ApiPublicSeedSevsRouteImport.update({
  id: '/api/public/seed-sevs',
  path: '/api/public/seed-sevs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResultsStreamElectionIdRoute =
  ApiPublicResultsStreamElectionIdRouteImport.update({
    id: '/api/public/results-stream/$electionId',
    path: '/api/public/results-stream/$electionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/setup/$token': typeof SetupTokenRoute
  '/vote/$electionId': typeof VoteElectionIdRouteWithChildren
  '/results/': typeof ResultsIndexRoute
  '/api/public/seed-sevs': typeof ApiPublicSeedSevsRoute
  '/vote/$electionId/cast': typeof VoteElectionIdCastRoute
  '/api/public/results-stream/$electionId': typeof ApiPublicResultsStreamElectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/setup/$token': typeof SetupTokenRoute
  '/vote/$electionId': typeof VoteElectionIdRouteWithChildren
  '/results': typeof ResultsIndexRoute
  '/api/public/seed-sevs': typeof ApiPublicSeedSevsRoute
  '/vote/$electionId/cast': typeof VoteElectionIdCastRoute
  '/api/public/results-stream/$electionId': typeof ApiPublicResultsStreamElectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/setup/$token': typeof SetupTokenRoute
  '/vote/$electionId': typeof VoteElectionIdRouteWithChildren
  '/results/': typeof ResultsIndexRoute
  '/api/public/seed-sevs': typeof ApiPublicSeedSevsRoute
  '/vote/$electionId/cast': typeof VoteElectionIdCastRoute
  '/api/public/results-stream/$electionId': typeof ApiPublicResultsStreamElectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/results/$electionId'
    | '/setup/$token'
    | '/vote/$electionId'
    | '/results/'
    | '/api/public/seed-sevs'
    | '/vote/$electionId/cast'
    | '/api/public/results-stream/$electionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/results/$electionId'
    | '/setup/$token'
    | '/vote/$electionId'
    | '/results'
    | '/api/public/seed-sevs'
    | '/vote/$electionId/cast'
    | '/api/public/results-stream/$electionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/results/$electionId'
    | '/setup/$token'
    | '/vote/$electionId'
    | '/results/'
    | '/api/public/seed-sevs'
    | '/vote/$electionId/cast'
    | '/api/public/results-stream/$electionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ResultsElectionIdRoute: typeof ResultsElectionIdRoute
  SetupTokenRoute: typeof SetupTokenRoute
  VoteElectionIdRoute: typeof VoteElectionIdRouteWithChildren
  ResultsIndexRoute: typeof ResultsIndexRoute
  ApiPublicSeedSevsRoute: typeof ApiPublicSeedSevsRoute
  ApiPublicResultsStreamElectionIdRoute: typeof ApiPublicResultsStreamElectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$electionId': {
      id: '/vote/$electionId'
      path: '/vote/$electionId'
      fullPath: '/vote/$electionId'
      preLoaderRoute: typeof VoteElectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$token': {
      id: '/setup/$token'
      path: '/setup/$token'
      fullPath: '/setup/$token'
      preLoaderRoute: typeof SetupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$electionId': {
      id: '/results/$electionId'
      path: '/results/$electionId'
      fullPath: '/results/$electionId'
      preLoaderRoute: typeof ResultsElectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$electionId/cast': {
      id: '/vote/$electionId/cast'
      path: '/cast'
      fullPath: '/vote/$electionId/cast'
      preLoaderRoute: typeof VoteElectionIdCastRouteImport
      parentRoute: typeof VoteElectionIdRoute
    }
    '/api/public/seed-sevs': {
      id: '/api/public/seed-sevs'
      path: '/api/public/seed-sevs'
      fullPath: '/api/public/seed-sevs'
      preLoaderRoute: typeof ApiPublicSeedSevsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/results-stream/$electionId': {
      id: '/api/public/results-stream/$electionId'
      path: '/api/public/results-stream/$electionId'
      fullPath: '/api/public/results-stream/$electionId'
      preLoaderRoute: typeof ApiPublicResultsStreamElectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VoteElectionIdRouteChildren {
  VoteElectionIdCastRoute: typeof VoteElectionIdCastRoute
}

const VoteElectionIdRouteChildren: VoteElectionIdRouteChildren = {
  VoteElectionIdCastRoute: VoteElectionIdCastRoute,
}

const VoteElectionIdRouteWithChildren = VoteElectionIdRoute._addFileChildren(
  VoteElectionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ResultsElectionIdRoute: ResultsElectionIdRoute,
  SetupTokenRoute: SetupTokenRoute,
  VoteElectionIdRoute: VoteElectionIdRouteWithChildren,
  ResultsIndexRoute: ResultsIndexRoute,
  ApiPublicSeedSevsRoute: ApiPublicSeedSevsRoute,
  ApiPublicResultsStreamElectionIdRoute: ApiPublicResultsStreamElectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
